version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: urlShortenerDB